name: Build and scan OCI images

on:
  # IC: for dev
  pull_request:
  #  schedule:
  #    # every day at 1:00AM UTC
  #    - cron: '5 3 * * *'

jobs:
  build-scan:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and scan for vulnerabilities
        run: |
          cd image-definitions/
          ./install-tools.sh
          ./setup.sh .
          ./apply-patches.sh
          ./build-scan.sh
      - name: Send vulnerability records
        run: |
          cd image-definitions/
          ./send-scan.sh ./trivy-reports
