name: Release to Charmhub

on:
  push:
    branches:
      - main
      - track/**

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  release:
    strategy:
      matrix:
        charm: ${{ fromJSON(needs.ci-tests.outputs.charm-paths) }}
    name: Release charm | ${{ matrix.charm }}
    needs:
      - ci-tests
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_edge.yaml@v38.0.0
    with:
      track: ${{ needs.ci-tests.outputs.track }}
      artifact-prefix: ${{ needs.ci-tests.outputs.artifact-prefix }}
      path-to-charm-directory: ${{ matrix.charm }}
    secrets:
      charmhub-token: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
    permissions:
      contents: write  # Needed to create git tags
